/**
 * Centralized backend API surface for ORIVONA demo pages.
 * Base URL: NEXT_PUBLIC_API_BASE_URL (default http://localhost:8080/api)
 */
export * from "@/src/lib/api/client";
export * from "@/src/lib/api/types";
export {
  createCustomerEventRequest,
  deleteCustomerEventRequest,
  extractAiRecommendations,
  extractEventRequest,
  normalizeEventRequest,
  fetchAdminSummary,
  fetchAiRecommendations,
  fetchCustomerEventRequests,
  fetchEventRequestById,
  buildMarketplaceQueryParams,
  fetchAccountProfile,
  updateAccountProfile,
  normalizeAccountProfile,
  extractMarketplaceItems,
  fetchMarketplace,
  fetchServiceById,
  normalizeMarketplaceItem,
  createVendorService,
  deleteVendorService,
  fetchCategories,
  fetchVendorProfile,
  fetchVendorServices,
  normalizeVendorProfile,
  normalizeVendorService,
  updateCustomerEventRequest,
  updateVendorService,
  fetchVendorDashboardSummary,
  fetchCustomerDashboardSummary,
  fetchAdminDashboardSummary,
  fetchFavorites,
  addFavorite,
  removeFavorite,
  createOfferRequest,
  fetchMyOfferRequests,
  fetchVendorOfferRequests,
  sendVendorOffer,
  rejectVendorOfferRequest,
  acceptCustomerOffer,
  rejectCustomerOffer,
  createReservation,
  fetchMyReservations,
  fetchVendorReservations,
  cancelReservation,
  confirmVendorReservation,
  completeVendorReservation,
  fetchServiceImages,
  addServiceImage,
  updateServiceImage,
  deleteServiceImage,
  fetchAiEventPlan,
  fetchAdminVendors,
  fetchAdminPendingVendors,
  approveAdminVendor,
  rejectAdminVendor,
  activateAdminVendor,
  deactivateAdminVendor,
  fetchAdminCategories,
  createAdminCategory,
  updateAdminCategory,
  deleteAdminCategory,
  fetchAdminUsers,
  activateAdminUser,
  deactivateAdminUser,
  fetchAdminServices,
  featureAdminService,
  unfeatureAdminService,
  fetchNotifications,
  markNotificationRead,
  markAllNotificationsRead,
  fetchConversations,
  fetchConversationMessages,
  createConversation,
  sendConversationMessage,
  fetchVendorAvailability,
  createVendorAvailability,
  deleteVendorAvailability,
  fetchServiceAvailability,
  fetchServiceReviews,
  submitServiceReview,
} from "@/src/lib/api/index";
export {
  fetchMyEventPlans,
  fetchEventPlanById,
  createEventPlan,
  updateEventPlan,
  deleteEventPlan,
  fetchEventPlanTasks,
  createEventPlanTask,
  updateEventPlanTask,
  deleteEventPlanTask,
  generateEventPlanTasks,
  fetchEventPlanGuests,
  createEventPlanGuest,
  updateEventPlanGuest,
  deleteEventPlanGuest,
  importDemoEventPlanGuests,
  updateGuestRsvp,
  fetchRsvpSummary,
  fetchQrInvite,
  fetchEventPlanSeating,
  createSeatingTable,
  updateSeatingTable,
  deleteSeatingTable,
  assignGuestToTable,
  fetchEventPlanReminders,
  generateEventPlanReminders,
} from "@/src/lib/api/eventPlans";
export {
  sendGuestInvite,
  sendGuestInvitesBulk,
  fetchInviteByToken,
  submitInviteRsvp,
  fetchInviteTicket,
  normalizeInviteDetails,
  normalizeInviteTicket,
} from "@/src/lib/api/invites";
export {
  fetchEventPlanPublicInvite,
  createEventPlanPublicInvite,
  disableEventPlanPublicInvite,
  fetchEventInviteByToken,
  verifyEventInviteGuest,
  submitEventInviteRsvp,
  fetchEventInviteTicket,
  normalizePublicEventInvite,
  normalizeEventInviteInfo,
} from "@/src/lib/api/publicEventInvite";
export {
  fetchVendorLeads,
  fetchVendorLeadById,
  updateVendorLeadStatus,
  addVendorLeadNote,
  fetchVendorAnalyticsSummary,
  fetchVendorAnalyticsServices,
  fetchVendorAnalyticsLeads,
  fetchVendorAnalyticsMonthly,
  trackServiceView,
  fetchServiceReviewSummary,
  fetchVendorReviewSummary,
} from "@/src/lib/api/vendorIntelligence";
export {
  fetchAiMoodboard,
  fetchAiBudgetOptimizer,
  fetchAiMissingServices,
  fetchAiStyleMatch,
  fetchAiSimilarEvents,
} from "@/src/lib/api/aiIntelligence";
export type { AiRecommendationsHttpResponse } from "@/src/lib/api/index";
